### PR TITLE
Added Cursor animation

### LINKED ISSUE #379: Feat: Adding animations to the Cursor
### Describe the feature

I want to add some animations while moving the cursor over the website, and clicking a button. This feature will surely enhance the website, and ensure an improved User experience.

### Add ScreenShots

I don't have screenshots right now, because I've not implemented it yet, but if assigned, I can assure not to disappoint you by any chance.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by harshmishra19**
I have added animation on the cursor
fixes #379 

https://github.com/Anushkabh/krishiconnect/assets/115486960/8e0b23da-fdde-4970-8d0e-4c1154acc832

### CODE REVIEW

**Comment by RitiChandak** [comment]
Please change the color something to green @Anushkabh any thought??

**Comment by harshmishra19** [comment]
Ok

**Comment by RitiChandak** [comment]
@harshmishra19 please wait for @Anushkabh to respond

**Comment by harshmishra19** [comment]
Any Update?

**Comment by harshmishra19** [comment]
@Anushkabh @RitiChandak

**Comment by Anushkabh** [comment]
@harshmishra19  can you add something relevant to the website .. maybe in the colour or design.. otherwise it looks fantastic

**Comment by harshmishra19** [comment]
https://github.com/Anushkabh/krishiconnect/assets/115486960/1de1502f-3925-4b2e-8cd6-370f1222f5bb

**Comment by harshmishra19** [comment]
@Anushkabh @RitiChandak

**Comment by RitiChandak** [comment]
image
 please resolve the conflicts

**Comment by harshmishra19** [comment]
Done @RitiChandak

**Comment by harshmishra19** [comment]
@RitiChandak @Anushkabh

**Comment by RitiChandak** [comment]
@harshmishra19 sorry for the late reply 

i can see you have done this for only home page what about other uniformity should maintain across the platform

**Pull request closed without merging**
