### PR TITLE
added logo in footer

### PR DESCRIPTION
**Pull request by Maheshwari-Love**
added the link to home page in footer by adding logo and click on it redirect to home oage

### CODE REVIEW

**Comment by RitiChandak** [comment]
image
 conflicting files please resolve and mention issue number

**Comment by RitiChandak** [comment]
issue number??

**Comment by Maheshwari-Love** [comment]
> issue number??

closed #919

**Comment by RitiChandak** [comment]
> image conflicting files please resolve and mention issue number

please resolve conflict

**Pull request closed without merging**
