### PR TITLE
Fixed Issue: #654 All social Icons added to footer of all pages 

### PR DESCRIPTION
**Pull request by SumithThota**
@Anushkabh, I have fixed Footer of all the pages by adding all social Icons 
Fixed Issue: #654 

# Before
## We had only 3 social icons
Screenshot 2024-07-03 171748

# After
Screenshot 2024-07-03 181736

I have updated to all the pages please check this Video 

https://github.com/Anushkabh/krishiconnect/assets/108344062/534a7f40-62cd-44a8-a354-253a9dacad93

### CODE REVIEW

**Comment by SumithThota** [comment]
@Anushkabh Check out this PR and add appropriate labels to itt

**Comment by himanshu-03** [comment]
Great!

**Comment by himanshu-03** [comment]
> @Anushkabh Check out this PR and add appropriate labels to itt

Solve merge conflicts

**Comment by SumithThota** [comment]
@himanshu-03 yes I just resolved all the conflicts, once check it

**Comment by himanshu-03** [comment]
hello @SumithThota !

The footer and the icons are better updated before.
Keep looking for more issues in the repo.
HappyCoding ✨

**Comment by SumithThota** [comment]
> Great!

@himanshu-03 but you have just appreciated 
Anyhow it's ok

**Pull request closed without merging**
