### PR TITLE
Made the Navbar of the FAQ page the same as the Navbar on other pages

### PR DESCRIPTION
**Pull request by Vibhu315**
#  **Related Issue**
NavBar of FAQ was different from other page's NavBar
Fixes: #482 

# **Description**
NavBar of FAQ was different from other page's navbar in the website . I Made the navbar of the FAQ page the same as the navbar on other pages of the website.
Fixed Issue: #482 

# Type of PR
- [x] Bug Fix

# Screenshots
## BEFORE:
image

## AFTER:
image

# CheckLists

- [x] I have made this change from my own.
- [x] My code follows the style guidelines of this project.
 - [x] I have performed a self-review of my own code.
 - [x] My changes generate no new warnings.
 - [x] I have tested the changes thoroughly before submitting this pull request.
 - [x]  I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by Anushkabh** [comment]
resolve conflicts

**Comment by Vibhu315** [comment]
Hey @Anushkabh , 
I have resolved the conflict you can review it and merge the changes.
Thank you.

**Comment by RitiChandak** [comment]
whats the navgitaion for faq

**Comment by Vibhu315** [comment]
Hey @RitiChandak ,
The Navabar of the FAQ page was different from the navabar of remaining pages in the website. So I made the navbar of FAQ page similar to other pages and commited the changes and made a pull request. You can view the pull request and merge it. 
Thank You

**Comment by RitiChandak** [comment]
My question is what should I click on to go to the FAQ page?


image
image

**Comment by Vibhu315** [comment]
I have shared a video with you, through which you can find the FAQ page in the website.

image

https://github.com/Anushkabh/krishiconnect/assets/93249125/e395a77a-7a59-4357-8fbd-6a5874defe03

**Pull request merged**
