### PR TITLE
Darkmode icon issue fixed 

### PR DESCRIPTION
**Pull request by HK853**
image
Fixed issue no #370

### CODE REVIEW

**Comment by RitiChandak** [comment]
@HK853 please correct it for homepage too.
image
image

**Comment by HK853** [comment]
done

**Comment by HK853** [comment]
once check it whether it is looking fine or not

**Comment by RitiChandak** [comment]
@HK853 If any help needed contact me

**Comment by RitiChandak** [comment]
Resolve the conflict and create a new PR

**Pull request closed without merging**
