### PR TITLE
Fixed | Cart total display on visiting cart 

### PR DESCRIPTION
**Pull request by AvinashShrivastav**
Resolved the issue with the cart total display upon accessing the cart. 

- Previously, when a user visited the cart with items already added, the subtotal was not visible. 
- Additionally, when the quantity of an item was increased or decreased, the subtotal would display in black text on a black background. 
- This has now been corrected, and the subtotal is displayed properly.

image

### CODE REVIEW

**Comment by Anushkabh** [comment]
@AvinashShrivastav MENTION THE ISSUE NUMBER

**Comment by AvinashShrivastav** [comment]
@Anushkabh This fix corresponds to issue #99 .

**Comment by AvinashShrivastav** [comment]
Hi @Anushkabh, there is a minor conflict in the CSS file regarding the color of the subtotal. You may choose any one of the options provided. The rest of the code resolves issue #99.
image

**Comment by himanshu-03** [comment]
Fixes #99

**Pull request merged**
