### PR TITLE
Enhanced the cart page

### PR DESCRIPTION
**Pull request by Amruta7203**
@RitiChandak @himanshu-03 I have made all the changes that were requested.. Review and merge this PR after adding relevant gssoc label considering my contribution. Thank you

Changed the opacity
Corrected font size for responsiveness
Removed the unwanted space between navbar and logo
Changed the text color
Added responsiveness

image
image
image

### CODE REVIEW

**Comment by RitiChandak** [comment]
What's the issue no.?

**Comment by Amruta7203** [comment]
> What's the issue no.?

#601

**Comment by Amruta7203** [comment]
@RitiChandak Pls merge this PR and add level 2 label to it considering my contribution. Thank you

**Comment by RitiChandak** [comment]
image
please resolve

**Pull request closed without merging**
