### PR TITLE
Change Logo of navbar and footer

### PR DESCRIPTION
**Pull request by Mandakini-S**
I have add two logos for Dark and Light background, updated logo of each pages . These changes are done under issue #376 .
Screenshots:
Screenshot from 2024-06-02 18-03-11

Screenshot from 2024-06-02 18-02-59

Aditionally , I have fix the image of tomato as mention in issue #327 .
Screenshot:
Screenshot from 2024-06-02 18-03-16

### CODE REVIEW

**Review by Anushkabh — APPROVED** [review]

**Comment by Anushkabh** [comment]
resolve conflicts

**Comment by Mandakini-S** [comment]
@Anushkabh I have resolved conflict. Can you merge it with the main?
Also , label this as GSSoC.

**Comment by himanshu-03** [comment]
Fixes #376

**Review by himanshu-03 — APPROVED** [review]

**Comment by himanshu-03** [comment]
Hey @Mandakini-S !
Great job there ✨

Please resolve the merge conflicts by syncing your repo with our repo.

**Comment by himanshu-03** [comment]
hey @Mandakini-S !

It's been 2 weeks since we hearf from you about the PR. We will wait for 2 more days before which if we didnt received a reply from you, we will have to close this PR in order to assign this issue to someone else.

**Comment by Mandakini-S** [comment]
Hi @himanshu-03 ,

Thank you for your patience. I've resolved the merge conflicts and updated the pull request. Please review the changes at your convenience.

**Review by himanshu-03 — CHANGES_REQUESTED** [review]
image

hey @Mandakini-S !

Please remove the files from the root folder because we already migrated them to src folder. The html files in the root folder except `index.html` must be deleted.

**Comment by Mandakini-S** [comment]
Hello @himanshu-03 !
The HTML files have been removed from the root folder as mentioned.

**Review by himanshu-03 — APPROVED** [review]
LGTM!

**Pull request merged**
