### PR TITLE
Feat::Same Navbar on All Pages #354

### PR DESCRIPTION
**Pull request by nishant0708**
Feat::Same Navbar on All Pages #354
-fixed navbar for all pages 

https://github.com/Anushkabh/krishiconnect/assets/101548649/dbf56ef9-8dc8-46a2-bb46-e0389f3eb10b

### CODE REVIEW

**Comment by nishant0708** [comment]
hey @Anushkabh if any changes needed please let me know

**Comment by RitiChandak** [comment]
@nishant0708 please make it same for contact too

**Comment by nishant0708** [comment]
Okay I will do it

**Comment by nishant0708** [comment]
@RitiChandak @Anushkabh now it is same for Contact too

**Pull request merged**
