### PR TITLE
Alligned Navbar

### PR DESCRIPTION
**Pull request by sailaja-adapa**
Hello Project Admin
I Alligned Navbar Perfectly - Solved #897
Kindly  Please go through this PR @RitiChandak 

p1

### CODE REVIEW

**Comment by sailaja-adapa** [comment]
@RitiChandak kindly please go through this PR

**Comment by sailaja-adapa** [comment]
@RitiChandak kindly please go through this PR

**Comment by sailaja-adapa** [comment]
@RitiChandak kindly please go through this PR

**Comment by RitiChandak** [comment]
image
please check it again

**Comment by sailaja-adapa** [comment]
Yeah okk @RitiChandak

**Comment by sailaja-adapa** [comment]
I will notify you soon once i am done with it

**Comment by sailaja-adapa** [comment]
@RitiChandak Can you please check once and let me know if still it looks like that

**Comment by RitiChandak** [comment]
there is merging conflict
image

**Comment by sailaja-adapa** [comment]
I will solve and update you soon @RitiChandak

**Comment by sailaja-adapa** [comment]
@RitiChandak Kindly go through this PR i solved the conflicts

**Comment by sailaja-adapa** [comment]
@RitiChandak Kindly Please add GSSOC'24 level label

**Comment by sailaja-adapa** [comment]
@RitiChandak Kindly Please add GSSOC'24 level label

**Comment by sailaja-adapa** [comment]
@RitiChandak Kindly Please add GSSOC'24 level label since it is already merged

**Comment by sailaja-adapa** [comment]
@RitiChandak kindly please add level label under GSSOC'24

**Comment by sailaja-adapa** [comment]
Since this is already merged @RitiChandak

**Comment by sailaja-adapa** [comment]
@RitiChandak please add GSSOC level label today is the last date upto 7 pm only

**Comment by sailaja-adapa** [comment]
@RitiChandak please add GSSOC level label today is the last date upto 7 pm only

**Comment by sailaja-adapa** [comment]
@RitiChandak please add GSSOC level label today is the last date upto 7 pm only

**Comment by sailaja-adapa** [comment]
@RitiChandak  please add GSSOC level label today is the last date upto 7 pm only

**Comment by sailaja-adapa** [comment]
@RitiChandak  please add GSSOC level label today is the last date upto 7 pm only

**Comment by RitiChandak** [comment]
i am extremely sorry

**Comment by sailaja-adapa** [comment]
That's fine @RitiChandak :) No need to say sorry

**Pull request merged**
