### PR TITLE
PRODUCT  SECTION UPDATED

### PR DESCRIPTION
**Pull request by Husan7**
#550 issue solved

By adding this feature Product section looks more attractive .
It's a Responsive animation and effect .

Before

Screenshot 2024-06-09 171218

AFTER

DESKTOP MODE

https://github.com/Anushkabh/krishiconnect/assets/162671639/1088316b-0184-400b-8389-b5ccafb9a7f3

MOBILE MODE

https://github.com/Anushkabh/krishiconnect/assets/162671639/513a2cc9-163c-4b1d-82e3-f79a39d65ffb

### CODE REVIEW

**Comment by Husan7** [comment]
@himanshu-03  please review my PR and merge it

**Review by himanshu-03 — CHANGES_REQUESTED** [review]
- `product.css` and `product.js`  should be in the desired directory under assets 
- You can look on the below link and see how your changes are looking on the website: [Link](https://krishiconnect-git-fork-husan7-main-anushkabhs-projects.vercel.app/)

**Comment by Husan7** [comment]
> * `product.css` and `product.js`  should be in the desired directory under assets
> * You can look on the below link and see how your changes are looking on the website: [Link](https://krishiconnect-git-fork-husan7-main-anushkabhs-projects.vercel.app/)

 Ok sir , I will arrange it

**Comment by himanshu-03** [comment]
image

Also, try to keep this card a little small its covering the whole page.
We dont need such big fonts, you can shorten the font size on the homepage as well as on the product card.

**Comment by himanshu-03** [comment]
There are conflicting merges and also, sync your repo with our latest changes most of the files are movied in specific directories.

**Comment by Husan7** [comment]
> There are conflicting merges and also, sync your repo with our latest changes most of the files are movied in specific directories.

I will submit another PR for this issue
So i clossed this PR

**Pull request closed without merging**
