### PR TITLE
Updated Testimonial Section

### PR DESCRIPTION
**Pull request by Hemashree21**
Resolved issue #342 

image

### CODE REVIEW

**Comment by Hemashree21** [comment]
@Anushkabh @RitiChandak can you please check and approve this pr?

**Comment by Anushkabh** [comment]
resolve conflicts

**Comment by Hemashree21** [comment]
@Anushkabh resolved

**Comment by Hemashree21** [comment]
@Anushkabh can you please check

**Comment by himanshu-03** [comment]
Hello @Hemashree21 !
Great job there .✨

I feel that the cards are too big for the testimonials it can be of the same size or a little bigger than our present one. Let me know your opinion on this!

**Comment by RitiChandak** [comment]
@Hemashree21, could you please resolve the conflict in the file index.html

**Comment by himanshu-03** [comment]
Hello @Hemashree21 !

Its been a while since this PR is opened and there are various merge conflicts and changes to be addressed even now. We will wait for 2 more days for a reply from your side, if not, unfortunately, we will have to close this PR and assign the issue to someone else.

**Pull request closed without merging**
