### PR TITLE
Improvised Wishlist

### PR DESCRIPTION
**Pull request by anagha-chaudhari**
Fixes Issue #626 

krishi_wishlistt

Please review the PR

### CODE REVIEW

**Review by himanshu-03 — CHANGES_REQUESTED** [review]
There are some issues in the page, please check

**Comment by anagha-chaudhari** [comment]
@himanshu-03 I think now the page shall be working fine, please review

**Comment by anagha-chaudhari** [comment]
Please review the prs @himanshu-03 @RitiChandak

**Comment by RitiChandak** [comment]
image
please look into it

**Comment by anagha-chaudhari** [comment]
@RitiChandak The issue has been resolved, please check

**Comment by anagha-chaudhari** [comment]
@RitiChandak @himanshu-03 I request you to merge the pr if possible as the gssoc coding period will be ending soon, thank you :)

**Pull request merged**
