### PR TITLE
Made the navbar sticky in all the pages .

### PR DESCRIPTION
**Pull request by meetarora10**
I have made the navbar sticky in all the pages .
Screenshot (936)
Screenshot (937)
Screenshot (938)
Screenshot (934)
Screenshot (935)
Screenshot (932)

### CODE REVIEW

**Comment by meetarora10** [comment]
@RitiChandak have a look .

**Comment by meetarora10** [comment]
@RitiChandak please review and merge .

**Comment by meetarora10** [comment]
Hey @RitiChandak please take a moment to review and merge .

**Comment by meetarora10** [comment]
@RitiChandak 
I have also modified the login page . In that page the contents were not properly on the screen but I have completely modifed the page and also made the navbar sticky .
**Before**
Screenshot (939)
**After**
Screenshot (972)

**Comment by RitiChandak** [comment]
image
please resolve the conflict and mention issue no.

**Comment by meetarora10** [comment]
@RitiChandak done .
Issue #856

**Comment by meetarora10** [comment]
@RitiChandak please review and merge

**Pull request merged**
