### PR TITLE
Added "Scroll Down Progress Bar" to the Website

### LINKED ISSUE #776: Feature Addition : Add "Scroll Down Progress Bar" Matching to Website Design Theme
### Describe the feature

Hey @Anushkabh, @RitiChandak and @himanshu-03

I would like to suggest adding **a scroll down progress bar** to the website to enhance user experience.

-  A scroll progress bar visually indicates how much of the page has been scrolled and how much is left, providing users with a better sense of their position on the page. 
- This feature can be especially helpful for long pages

### Use Case

- Enhances user experience by providing visual feedback.
- Useful for long pages or articles.
- Improves overall navigation and user satisfaction

### Add ScreenShots

like this:

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by MastanSayyad**
Hey @himanshu-03  | issue closes #776 

I have added **scroll down progress bar** across all the pages in the website 

image

https://github.com/Anushkabh/krishiconnect/assets/101971980/e3ae5915-5082-4d97-8079-ce0ce863281c

Please take a look and review it, Thank You!!

### CODE REVIEW

**Comment by MastanSayyad** [comment]
Hey @himanshu-03 I have just resolved the conflicts in 12 files, I request you to review and merge my PR first as I have made the changes in multiple files, if you merge other PR then I have to encounter with multiple merge conflicts each time

**Review by himanshu-03 — CHANGES_REQUESTED** [review]
image

This is what I can see in the deployment link.

**Comment by himanshu-03** [comment]
Please resolve merge conflicts.

**Comment by MastanSayyad** [comment]
> Please resolve merge conflicts.

I have resolved the issue pls check

**Comment by MastanSayyad** [comment]
Also If possible Could you please Update the label to level 2 or 3 as I have extended the Progress bar to other pages too which was very hectic as complex HTML files andI had to ensure not to broke any changes

**Comment by MastanSayyad** [comment]
@himanshu-03 pls merge this PR

**Comment by MastanSayyad** [comment]
@himanshu-03 Hey please merge this PR!!

**Comment by MastanSayyad** [comment]
@himanshu-03 if you are there then please merge this PR

**Comment by MastanSayyad** [comment]
Hi @himanshu-03 if you are there then please merge this PR

**Comment by MastanSayyad** [comment]
@himanshu-03 pls take a look at this PR

**Comment by MastanSayyad** [comment]
Hey @himanshu-03 Gssoc is going to end, pls merge this PR !

**Comment by MastanSayyad** [comment]
@himanshu-03 Please merge this PR

**Comment by MastanSayyad** [comment]
@RitiChandak pls merge this PR as the gssoc is near to its end

**Comment by RitiChandak** [comment]
image
this is what i am seeing

**Comment by MastanSayyad** [comment]
@RitiChandak It is due to new merge changes, i will fix it

**Comment by MastanSayyad** [comment]
@RitiChandak I have fixed it, please take a look and review it! and add the labels accordingly!

**Pull request merged**
