### PR TITLE
navbar elements added 

### PR DESCRIPTION
**Pull request by NitinChakrawarti**
About us , contact us and back to home button added in navbar,

Earlier there is no button to get back to home page which is making UI very difficult, when user is not in home page.

My issue no.  #81

###  **Before changes**

https://github.com/Anushkabh/krishiconnect/assets/149225785/ddd4819f-702a-496e-8744-ee7b21b23b1f

### **After changes** 

https://github.com/Anushkabh/krishiconnect/assets/149225785/3a3ad04d-9ca4-4a89-82f6-85a83e27c266

Now user can easily navigate back to home button in different pages of website for e.g. In about page, In contact page , In  Shop page and so on.

### CODE REVIEW

**Comment by Anushkabh** [comment]
@NitinChakrawarti good work !
remove contact us from navbar

**Comment by NitinChakrawarti** [comment]
> @NitinChakrawarti good work ! remove contact us from navbar

@Anushkabh Done, please assign  this PR to me, and add label in PR.

**Comment by NitinChakrawarti** [comment]
@Anushkabh Thanks for this wonderful opportunity to work on this project.

**Comment by himanshu-03** [comment]
Fixes #81

**Pull request merged**
