### PR TITLE
Added Sign-in/Sign-up page for Buyers

### LINKED ISSUE #547: Add a login/signup page for buyers as well
### Describe the feature

adding a login/signup page is important as that way they can keep a track of their transactions and orders and access their wishlist and cart and put it in the nav bar for easy access

### Add ScreenShots

Design a signup/sign in page  something of this sort
image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by samarsajad**
## Description
Added an option for signin/signup for the buyers which leads to the signin/signup form for the buyers.
## Screenshots

https://github.com/Anushkabh/krishiconnect/assets/142666229/3b4ec4d5-c3a0-48b2-91fa-536805cd03bb

### CODE REVIEW

**Comment by samarsajad** [comment]
Please review my pull request @Anushkabh

**Comment by samarsajad** [comment]
Please review my pull request @himanshu-03

**Comment by samarsajad** [comment]
Please review my pull request @himanshu-03 @Anushkabh

**Comment by himanshu-03** [comment]
Hey @samarsajad !

Please resolve the merge conflicts. Our repo underwent with a series of major changes since last 2 weeks. I request you to please sync the latest changes and resolve the conficts raised.

**Comment by himanshu-03** [comment]
Make sure the images, style files and the scripts are in the desired directory.

**Comment by samarsajad** [comment]
> Make sure the images, style files and the scripts are in the desired directory.

can u please mention where do you want all these files ? @himanshu-03

**Comment by himanshu-03** [comment]
> Author

You can check the repo and see that we have all this files in the assets directory.
We have css, js, images directory respectively over there.

**Comment by samarsajad** [comment]
Made the changes. Kindly take a look  @himanshu-03 @Anushkabh

**Comment by himanshu-03** [comment]
LGTM!

**Review by RitiChandak — CHANGES_REQUESTED** [review]
image
after login i am getting an error page please check

**Comment by samarsajad** [comment]
I made the changes and it is working as expected. Please review it and let me know if you want any more changes @RitiChandak @himanshu-03

**Comment by samarsajad** [comment]
Can I please open a new pull request for this issue as I am Facing issues in pushing the changes in the same branch? @himanshu-03 @RitiChandak

**Comment by samarsajad** [comment]
I made the changes please take a look @himanshu-03 @RitiChandak @Anushkabh

**Comment by samarsajad** [comment]
I created a new pull request because this one had some issues that couldn'tr be solved . PTAL #854 @himanshu-03 @RitiChandak @Anushkabh

**Pull request closed without merging**
