### PR TITLE
fix: Made the LEGAL Section of footer responsive in mobile-view

### LINKED ISSUE #927: BUG: The LEGAL section of footer is not center in mobile-view.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

- The LEGAL section of footer is not center in mobile-view.
- This should be aligned at center for good user experience.

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by vishanurag**
# Fixes #927

# Description:
- Made the LEGAL Section of footer responsive in mobile-view.
- Now, the LEGAL section is looking responsive in mobile-view.

# Screenshort:

Screenshot 2024-08-05 221545

### @RitiChandak @Anushkabh please review & merge my pull-request under GSSoC'24

### CODE REVIEW

**Comment by vishanurag** [comment]
@RitiChandak @Anushkabh please review & merge my pull-request under GSSoC'24

**Comment by vishanurag** [comment]
@RitiChandak can you please add GSsoc label level1 in this pr because you added level1 on the issue #927

**Comment by vishanurag** [comment]
Please add level1 label in this pr.

**Comment by vishanurag** [comment]
@RitiChandak Please add level1 label in this pr. because without level label I will not be able to get points. Hope you understand 🙏.

**Comment by RitiChandak** [comment]
The changes with only one line are not allowed to give level.

**Comment by vishanurag** [comment]
It took time to debug the code & I tried my best to make as minimal changes as possible. Initially I made changes via using css media-queries but then I researched about bootstrap classes inorder to make as less change as possible. Please add level1 for this PR. it was my first PR on this repo. 🙏

**Pull request merged**
