### PR TITLE
change the footer and the title page logo

### PR DESCRIPTION
**Pull request by jayanththalla**
In the footer, I changed the space between the container social media links and the social media links
On main page, the logo was changed to make the navbar logo main page the same 
Bottom of the footer I removed background color of the copyright to look good
please label gssoc @Pa

### CODE REVIEW

**Comment by Anushkabh** [comment]
ss?

**Comment by RitiChandak** [comment]
@jayanththalla what's the issue number??
Please add Screenshot

**Comment by himanshu-03** [comment]
Fixes #331

**Comment by jayanththalla** [comment]
i have made pr why the issue was open again @pa

**Comment by himanshu-03** [comment]
Hello @jayanththalla !

Can you please sync your repo once?
Our repo underwent major changes during last 2 weeks.

**Pull request closed without merging**
