### PR TITLE
add social icon on right of screen and added hovering effect

### LINKED ISSUE #724: Feat: Add actual colour of social icon on hovering in footer .
### Describe the feature

when we hover on social icon in footer it will convert to its original colour .

I am sure that users will definately like this feature  . 

### Add ScreenShots

before : 

https://github.com/Anushkabh/krishiconnect/assets/159682348/7d3761bd-c70c-45f2-8527-cc72d104e28a

want to make it like this : 

https://github.com/Anushkabh/krishiconnect/assets/159682348/6549c4bc-2c8d-4997-a764-83c5e2e1921c

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by ANKeshri**
fixes #724 

- add hovering effect to social icons of footer . 
- add social icons to right of home page .

1. hover in footer : 

https://github.com/Anushkabh/krishiconnect/assets/159682348/ae5c06f1-246b-4e25-88f9-3ca1b45b0bdb

2. social icon on right of home page 

https://github.com/Anushkabh/krishiconnect/assets/159682348/26a8129c-91d1-4ed7-8edd-ae3ecf0ccfc9

3.  it is fixed in one position  

https://github.com/Anushkabh/krishiconnect/assets/159682348/9bf8526e-99d3-4575-862e-d96b49bc43ff

### CODE REVIEW

**Comment by ANKeshri** [comment]
@Anushkabh @himanshu-03 please review my pr and merge it under gssoc labels .

if possible please give it level 2 .

**Comment by himanshu-03** [comment]
Hey @ANKeshri !

Please make sure the socials remains on all website pages not only index.html and resolv the conflict.

**Comment by ANKeshri** [comment]
> Hey @ANKeshri !
> 
> Please make sure the socials remains on all website pages not only index.html and resolv the conflict.

@himanshu-03 Sure I will do that .

**Comment by ANKeshri** [comment]
@himanshu-03 added right screen icons to all the pages and add 2 more social icon to footer and made the hover effect in every icons please review it once and merge my pr

**Comment by himanshu-03** [comment]
Great!

**Pull request merged**
