### PR TITLE
Feat:Footer Is Not Going With Ui #610

### LINKED ISSUE #610: Feat:Footer Is Not Going With Ui
### Describe the feature

Currently The Footer is very much bad which is affecting the asthetics of the website . I want to fix that

### Add ScreenShots

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by nishant0708**
Feat:Footer Is Not Going With Ui #610

closes #610 

https://github.com/Anushkabh/krishiconnect/assets/101548649/509f4045-15a6-4bc3-a75a-c463323d1ec6

### CODE REVIEW

**Comment by nishant0708** [comment]
hey @himanshu-03 please check this pr I have made footer consistent as asked in all the pages so can you can assign it level 3

**Comment by himanshu-03** [comment]
> hey @himanshu-03 please check this pr I have made footer consistent as asked in all the pages so can you can assign it level 3. And can you please merge pr #584 first before this because i accidently forked it from the branch present in #584

You can sync it later by changing your remote origin @nishant0708

**Comment by himanshu-03** [comment]
@nishant0708 Please reply to me about the pr #584

**Review by himanshu-03 — CHANGES_REQUESTED** [review]
image

The fonts in the left description doesnt match with the fonts in the right also the image doesnt look good try changing the dimeensions or width of the image to make it look accurate. Right now it looks too much stretched

**Comment by nishant0708** [comment]
> image
> 
> The fonts in the left description doesnt match with the fonts in the right also the image doesnt look good try changing the dimeensions or width of the image to make it look accurate. Right now it looks too much stretched

Hey @himanshu-03 actually the image dimension are exactly same which are in navbar . description  i am fixing it

**Comment by himanshu-03** [comment]
> > image
> > The fonts in the left description doesnt match with the fonts in the right also the image doesnt look good try changing the dimeensions or width of the image to make it look accurate. Right now it looks too much stretched
> 
> Hey @himanshu-03 actually the image dimension are exactly same which are in navbar . description i am fixing it. it was intentional to make it look like navbar but if you want i can change that

Yes you can change and there are still many fiiles where header and footer are not there can you add those in all off them
?

**Comment by nishant0708** [comment]
> > > image
> > > The fonts in the left description doesnt match with the fonts in the right also the image doesnt look good try changing the dimeensions or width of the image to make it look accurate. Right now it looks too much stretched
> > 
> > 
> > Hey @himanshu-03 actually the image dimension are exactly same which are in navbar . description i am fixing it. it was intentional to make it look like navbar but if you want i can change that
> 
> Yes you can change and there are still many fiiles where header and footer are not there can you add those in all off them ?

hey @himanshu-03 currently i have changed only those files to which user can navigate  but okay let change all the files which contain footer

**Comment by himanshu-03** [comment]
> > > > image
> > > > The fonts in the left description doesnt match with the fonts in the right also the image doesnt look good try changing the dimeensions or width of the image to make it look accurate. Right now it looks too much stretched
> > > 
> > > 
> > > Hey @himanshu-03 actually the image dimension are exactly same which are in navbar . description i am fixing it. it was intentional to make it look like navbar but if you want i can change that
> > 
> > 
> > Yes you can change and there are still many fiiles where header and footer are not there can you add those in all off them ?
> 
> hey @himanshu-03 currently i have changed only those files to which user can navigate but okay let change all the files which contain footer. does it look better? image

Make the desctiptions left aligned aogn with the logo too. dont justify the content and please make sure we have header footer in all our pages.

**Comment by himanshu-03** [comment]
image

@nishant0708 thee text and logo are still no left aligned.

**Comment by himanshu-03** [comment]
Also @nishant0708 
image

there are some changes in our footer, the miscellaneous is changed with FAQ and a link is added too the faq page (Do make a note of it!)

**Comment by nishant0708** [comment]
> Also @nishant0708 image
> 
> there are some changes in our footer, the miscellaneous is changed with FAQ and a link is added too the faq page (Do make a note of it!)

Hey frequently Asked questions is too long should I add FAQ

**Comment by nishant0708** [comment]
> Also @nishant0708 image
> 
> there are some changes in our footer, the miscellaneous is changed with FAQ and a link is added too the faq page (Do make a note of it!)



> image
> 
> @nishant0708 thee text and logo are still no left aligned.

I am still working i will let you know when it will be ready for review

**Comment by himanshu-03** [comment]
> > Also @nishant0708 image
> > 
> > there are some changes in our footer, the miscellaneous is changed with FAQ and a link is added too the faq page (Do make a note of it!)
> 
> Hey frequently Asked questions is too long should I add FAQ

Yes you can!

**Comment by nishant0708** [comment]
hey @himanshu-03 you can check it now .  I have added my code to all pages but the problem is there difference of import 3rd party stylesheet which is causing problems . And to Fix that takes a lot of time so can i just raise another pr for that because genuinely its a lot of work

**Comment by nishant0708** [comment]
image

**Review by himanshu-03 — APPROVED** [review]
LGTM!

**Comment by himanshu-03** [comment]
> Just wait a sec doing it nos

Why did you closed this PR?

**Comment by nishant0708** [comment]
> > Just wait a sec doing it nos
> 
> Why did you closed this PR?

I don't know it happened automatically

**Comment by nishant0708** [comment]
> > > Just wait a sec doing it nos
> > 
> > 
> > Why did you closed this PR?
> 
> I don't know it happened automatically

Wait I will reopen new pr

**Comment by nishant0708** [comment]
> > > > > Just wait a sec doing it nos
> > > > 
> > > > 
> > > > Why did you closed this PR?
> > > 
> > > 
> > > I don't know it happened automatically
> > 
> > 
> > Wait I will reopen new pr
> 
> You can be in the PR itseldd I will reopen this PR

Yes please reopen this if you can

**Comment by nishant0708** [comment]
Hey @himanshu-03 check it now

**Review by himanshu-03 — APPROVED** [review]
LGTM!

**Comment by nishant0708** [comment]
Hey @himanshu-03 it is not assigned to me can you assign it to me

**Comment by himanshu-03** [comment]
> Hey @himanshu-03 it is not assigned to me can you assign it to me

You were already assigned this in issue, so no problem in that.

**Pull request merged**
