### PR TITLE
added blog page - fixes #635

### LINKED ISSUE #635: Feat: Create blog page
### Describe the feature

I would like to add a blog page for this website. It includes blog articles regarding buying guides, product categories, technology related etc. topics.

### Add ScreenShots

Screenshot 2024-06-19 081924
Screenshot 2024-06-19 081956

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by DharshiBalasubramaniyam**
This pr fixes #635 

Things I have done:

1. Created s separate page for blogs.
2. Created sample blogs data (blogData.js).
3. Updated the footer in all pages and added blog page link.
4. Added Trending blogs section in index.html.

Screenshots/Videos

https://github.com/Anushkabh/krishiconnect/assets/139672976/abf49573-43ea-452d-9ee1-d612e0cbae63

https://github.com/Anushkabh/krishiconnect/assets/139672976/2e82d1e6-2c85-4594-ad0a-bf9d345ec433

Screenshot 2024-07-02 200600

Kindly let me know if any changes required!

### CODE REVIEW

**Comment by himanshu-03** [comment]
image

The nav content should go down instead of the heading going up. Also resolve merge conflicts.

**Comment by himanshu-03** [comment]
Also, try to add a little transparency over the image b ackground in the blogs section so the heading is visible properly.

**Comment by DharshiBalasubramaniyam** [comment]
> image
> 
> The nav content should go down instead of the heading going up. Also resolve merge conflicts.

Sorry, I didn't get your point(The nav content should go down instead of the heading going up.) properly.

**Comment by himanshu-03** [comment]
> > image
> > The nav content should go down instead of the heading going up. Also resolve merge conflicts.
> 
> Sorry, I didn't get your point(The nav content should go down instead of the heading going up.) properly.

Useful Sections heading should be in line with other headings

**Comment by DharshiBalasubramaniyam** [comment]
> > > image
> > > The nav content should go down instead of the heading going up. Also resolve merge conflicts.
> > 
> > 
> > Sorry, I didn't get your point(The nav content should go down instead of the heading going up.) properly.
> 
> Useful Sections heading should be in line with other headings

Sure. got it

**Comment by DharshiBalasubramaniyam** [comment]
@himanshu-03  I have made required changes now!

**Comment by himanshu-03** [comment]
LGTM!

**Pull request merged**
