### PR TITLE
Dark theme working now on cantact.html

### LINKED ISSUE #598: BUG: Dark mode toggle button not working in Contactus page.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The light mode to dark mode toggle button is not working in contact us page. The button is not clickable and also theme is not changing.

https://github.com/Anushkabh/krishiconnect/assets/121669832/12e8b9e1-a299-4d8d-834f-8b13dfd572f0

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by nagalakshmi08**
Closes #598 

The light theme to dark theme toggle button is now working in contact us page.

https://github.com/Anushkabh/krishiconnect/assets/121669832/e4f7c01b-5c87-4ba5-8206-abe77e2136b8

### CODE REVIEW

**Comment by himanshu-03** [comment]
> Closes #598
> 
> The light theme to dark theme toggle button is now working in contact us page.
> 
>  340386357-7382807b-3226-4d87-b531-8c7f0139e7c6.mp4

image

this looks so odd and disoriented dont you think?

**Comment by nagalakshmi08** [comment]
> > Closes #598
> > The light theme to dark theme toggle button is now working in contact us page.
> > 340386357-7382807b-3226-4d87-b531-8c7f0139e7c6.mp4
> 
> image
> 
> this looks so odd and disoriented dont you think?

I have raised the issue regarding the button functionality, so I just added the toggling feature. The styling remains the same as before. I can update the styling if needed.

**Comment by himanshu-03** [comment]
> > > Closes #598
> > > The light theme to dark theme toggle button is now working in contact us page.
> > > 340386357-7382807b-3226-4d87-b531-8c7f0139e7c6.mp4
> > 
> > 
> > image
> > this looks so odd and disoriented dont you think?
> 
> I have raised the issue regarding the button functionality, so I just added the toggling feature. The styling remains the same as before. I can update the styling if needed.

yes please

**Comment by nagalakshmi08** [comment]
Hi @himanshu-03 , I have made the changes and created a new PR #840 , Please check it once.

**Comment by RitiChandak** [comment]
Please Resolve the conflicting files
src/contact.html

**Comment by nagalakshmi08** [comment]
> Please Resolve the conflicting files src/contact.html

I have raised a new PR #840  on this issue, where there are no conflicts. Please check that once.

**Pull request closed without merging**
