### PR TITLE
added a home section in all page

### PR DESCRIPTION
**Pull request by souravgope**
hey @Anushkabh i added a home section in all the page form which they can directly goes to home page . Please accept the Pr and level it 
Screenshot (188)

### CODE REVIEW

**Comment by Anushkabh** [comment]
issue number?

**Comment by souravgope** [comment]
#287

**Comment by souravgope** [comment]
@Anushkabh  please merge it and label it

**Comment by Anushkabh** [comment]
resolve the conflicts by pulling the latest code

**Comment by souravgope** [comment]
hey @Anushkabh  please merge it i resolved

**Comment by RitiChandak** [comment]
image
resolve the conflicts

**Comment by RitiChandak** [comment]
Resolve the conflict and create a new PR
image

**Pull request closed without merging**
