### PR TITLE
Updated Testimonials Section

### PR DESCRIPTION
**Pull request by Hemashree21**
Resolved issue #342 

Screenshot 2024-06-01 110647

@Anushkabh I have updated the testimonials section and I have also made it responsive. Can you please check and let me know if any changes are required?

### CODE REVIEW

**Comment by RitiChandak** [comment]
image
@Hemashree21 Please remove the conflicts 
the conflicting file is index.html

**Comment by Hemashree21** [comment]
@RitiChandak I removed it

**Comment by RitiChandak** [comment]
@Hemashree21 
image
there are 2 conflicts Please remove it.

**Comment by Hemashree21** [comment]
@RitiChandak Its resolved now

image

**Pull request closed without merging**
