### PR TITLE
fix FAQ section by reordering questions #8

### PR DESCRIPTION
**Pull request by MehekFatima**
The FAQ section on the organization's website currently displays questions in a disordered sequence, which may disrupt user experience and clarity. To address this issue, I have reordered the questions to improve the flow and organization of the FAQ section and added mail to link.

### CODE REVIEW

**Comment by MehekFatima** [comment]
I kindly request @Anushkabh @nandu-99  to review the changes and provide feedback. If any further adjustments are needed, please let me know, and I will be happy to make them.

Thank you for your attention to this matter.

**Comment by Anushkabh** [comment]
@MehekFatima  kindly mention the issue number

**Comment by MehekFatima** [comment]
@Anushkabh I've mentioned the issue number (8). Please review the changes.

**Review by Anushkabh — APPROVED** [review]

**Comment by himanshu-03** [comment]
Fixes #8

**Pull request merged**
