### PR TITLE
Fix | Cart Item Issue#563

### PR DESCRIPTION
**Pull request by AvinashShrivastav**
https://github.com/Anushkabh/krishiconnect/assets/110047194/73e0ec3a-d3d8-4577-9650-9272a4675784

Resolved the bug affecting the cart item quantity; now, if the quantity decreases to 0, the item is automatically removed from the cart.

### CODE REVIEW

**Comment by himanshu-03** [comment]
Fixes #563

**Comment by RitiChandak** [comment]
@AvinashShrivastav there are conflicting file please resolve it

**Comment by AvinashShrivastav** [comment]
Hey @himanshu-03 , I have resolved the conflict. Kindly look into it

**Comment by AvinashShrivastav** [comment]
Hey @Anushkabh , there were issues with shop.html file at the time of merge which I resolved. Now since the branch was not merged, new issues in cart.js has arisen. Kindly give me permission to resolve the issues.

**Comment by AvinashShrivastav** [comment]
Hey @himanshu-03 , is this still active? or shall i create a new pull request?

**Comment by himanshu-03** [comment]
Hey @AvinashShrivastav  !

Please resolve the merge conflicts. Our repo underwent with a series of major changes since last 2 weeks. I request you to please sync the latest changes and resolve the conficts raised.

**Comment by AvinashShrivastav** [comment]
Hi @himanshu-03, the issue has been resolved, but it wasn't merged due to some conflicts. As I lacked the rights to resolve them, I've created another pull request with the changes, aligned with the newly updated codebase.
Please close this pull request and proceed to merge the new one.

**Pull request closed without merging**
