### PR TITLE
Mail to and tel added in the anchor tag

### PR DESCRIPTION
**Pull request by RamakrushnaBiswal**
Mail to and tel added in the anchor tag

https://github.com/Anushkabh/krishiconnect/assets/125277258/5242b4c3-7bcb-45ee-9b1b-2e92372f4822

### CODE REVIEW

**Comment by RamakrushnaBiswal** [comment]
@RitiChandak please review the PR

**Comment by RitiChandak** [comment]
@RamakrushnaBiswal Please do it everywhere

**Comment by RamakrushnaBiswal** [comment]
Ok

**Comment by RamakrushnaBiswal** [comment]
issue #393 solved

**Comment by RamakrushnaBiswal** [comment]
@RitiChandak please review the PR

**Comment by Anushkabh** [comment]
resolve conflicts

**Comment by RamakrushnaBiswal** [comment]
@RitiChandak @Anushkabh please review the PR

**Comment by RitiChandak** [comment]
image
Resolve the conflict and create a new PR

**Pull request closed without merging**
