### PR TITLE
Feat: Show the number of items in the cart as like Wishlist

### PR DESCRIPTION
**Pull request by SrinivasDevolper**
Issue No: #629

krishi website error1

**If it's not good, please assign me again I will do it better**

### CODE REVIEW

**Review by himanshu-03 — CHANGES_REQUESTED** [review]
image

Why are there two carts and I asked  you to do this for wishlist as well.

**Comment by SrinivasDevolper** [comment]
> image
> 
> Why are there two carts and I asked you to do this for wishlist as well.

**No, I displayed it as a wishlist and I only added one cart**

https://github.com/Anushkabh/krishiconnect/assets/121508628/9781c5c4-9027-4bb7-be60-3b2048d49514

**Comment by SrinivasDevolper** [comment]
I checked all the pages but it only has one cart. There are not many carts
If you get that error show me in detail, I can do it better

**Comment by himanshu-03** [comment]
https://krishiconnect-izedv7zh0-anushkabhs-projects.vercel.app/

This is what the deployment link shows.

**Pull request closed without merging**
