### PR TITLE
Updated chatbot #789

### PR DESCRIPTION
**Pull request by DevNandini02**
Made a chatbot that could answer user queries using the given knowledge base as well as AI. (Issue No. #789)

Before changes
krishi_bug3

After changes

https://github.com/Anushkabh/krishiconnect/assets/124669890/7ceb6f53-ebb4-42ae-aeb7-a103f17ebfce

### CODE REVIEW

**Comment by DevNandini02** [comment]
@RitiChandak please review my PR and merge it.

**Comment by DevNandini02** [comment]
@Anushkabh please review this PR.

**Comment by DevNandini02** [comment]
@Anushkabh its been 3 weeks already, please review the PR.

**Comment by RitiChandak** [comment]
@DevNandini02 sorry for the delay 
the changes you made have created this white box please look into it 
image

**Comment by DevNandini02** [comment]
> @DevNandini02 sorry for the delay the changes you made have created this white box please look into it image

@RitiChandak I'll correct it as soon as possible.

**Comment by DevNandini02** [comment]
@RitiChandak i have sent another PR correcting this issue. please check.

**Pull request closed without merging**
