### PR TITLE
PRODUCT SECTION UPDATE

### PR DESCRIPTION
**Pull request by Husan7**
#550 ISSUE SOLVED

SIZE REDUCED OF CARD & NO CONFLICT NOW ( RENIEW OF PR #698)

Screenshot 2024-07-01 142018

### CODE REVIEW

**Comment by Husan7** [comment]
@himanshu-03  PLEASE CHECK IT NOW

**Review by himanshu-03 — CHANGES_REQUESTED** [review]
image

The images are too big and the currency is in Dollars.

**Comment by Husan7** [comment]
@himanshu-03 please check it now 
image size and currency updated

**Review by himanshu-03 — CHANGES_REQUESTED** [review]
image

The whole website is zoomed out.

**Comment by Husan7** [comment]
@himanshu-03  please check it now 
IS it okay everything now

**Comment by himanshu-03** [comment]
> @himanshu-03 please check it now IS it okay everything now

image

**Pull request closed without merging**
