### PR TITLE
added the hover effect on divs in login page of src

### LINKED ISSUE #702: Feat:Adding same effect as are you buyer page in seller page
### Describe the feature

The hover animation of why krish connect in buyer page is very good but it is not implemented in seller page would like to add that 

### Add ScreenShots

image
image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by YadlaMani**
before 
image
after 
image
# Closes #702

### CODE REVIEW

**Review by himanshu-03 — CHANGES_REQUESTED** [review]
This is how it looks in the homepage

  > image

This is how it is looking in your changes at the seller page

  > image

Its tottaly disorganized the headers and all have changed.

**Comment by YadlaMani** [comment]
@himanshu-03 okay i will try to change completely

**Comment by YadlaMani** [comment]
@himanshu-03 bro it's like that from starting it's a different page you guys have not changed the navbar in src/login.html which have seller page so it's like that would you like me to change that too then i can change it

**Comment by himanshu-03** [comment]
> @himanshu-03 bro it's like that from starting it's a different page you guys have not changed the navbar in src/login.html which have seller page so it's like that would you like me to change that too then i can change it

image

Can you see it is normal in the hosted and latest website

**Pull request closed without merging**
