### PR TITLE
Fix | Cart item responsiveness issue#135

### PR DESCRIPTION
**Pull request by AvinashShrivastav**
Resolved issue #135 where longer names were not displaying correctly. Additionally, updated the appearance of the increase/decrease quantity button.

https://github.com/Anushkabh/krishiconnect/assets/110047194/54244e1c-7ac5-4974-88f0-f1e18d54dde8

### CODE REVIEW

**Comment by Anushkabh** [comment]
Resolve the conflicts

**Comment by AvinashShrivastav** [comment]
Hey @Anushkabh, I have resolved the conflict and have tested at my end. Kindly check.

**Comment by AvinashShrivastav** [comment]
Hey @Anushkabh, Is there anything else do  I need to do?

**Comment by himanshu-03** [comment]
Fixes #135

**Pull request merged**
