### PR TITLE
Alignment of same color in why krishniconnect

### PR DESCRIPTION
**Pull request by 1754riya**
### Issue number : 
#509

### Description:
Alignment of the same color in why krishniconnect. The uneven colors don't look good.

Before:
Screenshot (88)

After:
Screenshot (91)

### CODE REVIEW

**Comment by Anushkabh** [comment]
resolve conflicts

**Comment by 1754riya** [comment]
@Anushkabh, I have made changes. Please merge my pull request with the same color alignment.

**Comment by RitiChandak** [comment]
Resolve the conflict and create a new PR

**Comment by himanshu-03** [comment]
Stale!

**Pull request closed without merging**
