### PR TITLE
Added links to the footer and changed the logo in the footer on all pages

### LINKED ISSUE #712: Feat: Adding Links to the Footer and Changing the Logo in the Footer
### Describe the feature

- The logo in the Footer should be replaced with the logo of Header
- We will be having different individual pages for each category, so those must be linked in the footer.
- The FAQ link must be added and connected with the FAQ page in the footer.

### Add ScreenShots

- Logo in Footer (Currently)
    > image

- Logo in Footer (After doing the mentioned changes should look like)
    > image

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

### PR DESCRIPTION
**Pull request by AsmitaMishra24**
fixes #712 

Description:
- Added links to the footer on all pages.
- Changed the logo in the footer on all pages.
- Redirected pages that have not yet been created to the same page.

Screenshot:-
https://github.com/Anushkabh/krishiconnect/assets/146121869/8f323f05-e7ab-4865-98cd-244900c578de

### CODE REVIEW

**Comment by AsmitaMishra24** [comment]
@himanshu-03, I've added links to the footer and changed the logo in the footer on all pages. Please evaluate the feature and consider upgrading its level to Level 2 if it meets your expectations.

**Review by himanshu-03 — APPROVED** [review]
LGTM!

**Comment by himanshu-03** [comment]
> @himanshu-03, I've added links to the footer and changed the logo in the footer on all pages. Please evaluate the feature and consider upgrading its level to Level 2 if it meets your expectations.

Hey! since this was an issue where we needed to jsut add footer on all pages it was the same code. Thus, it will be counted as a level 1 contribution.

**Comment by AsmitaMishra24** [comment]
> > @himanshu-03, I've added links to the footer and changed the logo in the footer on all pages. Please evaluate the feature and consider upgrading its level to Level 2 if it meets your expectations.
> 
> Hey! since this was an issue where we needed to jsut add footer on all pages it was the same code. Thus, it will be counted as a level 1 contribution.

Ok

**Pull request merged**
