### PR TITLE
Nav Responsive

### PR DESCRIPTION
**Pull request by Rohitha-pudu**
#374

### CODE REVIEW

**Comment by RitiChandak** [comment]
@Rohitha-pudu please provide screenshot

**Comment by Rohitha-pudu** [comment]
> @Rohitha-pudu please provide screenshot

of the website

**Comment by Rohitha-pudu** [comment]
image
image
image

**Comment by RitiChandak** [comment]
@Rohitha-pudu of the changes you have made

**Comment by Rohitha-pudu** [comment]
> @Rohitha-pudu of the changes you have made

i changed all the nav's in all the pages with items space too

**Comment by Rohitha-pudu** [comment]
> > @Rohitha-pudu of the changes you have made
> 
> i changed all the nav's in all the pages with items space too and removed some bugs in wishlist mobile view

**Comment by himanshu-03** [comment]
Fixes #374

**Pull request merged**
