### PR TITLE
Replaced Rp with ₹

### LINKED ISSUE #634: Feat:The cost is shown in rp it should be changed to  ₹ symbol
### Describe the feature

The symbol of showing cost symbol should be changed 

### Add ScreenShots

image

I want to change the rp to ₹

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Saipradyumnagoud**
Replaced rp with ₹ because ecommerce websites dont have rp they have ₹ only .
closes #634

### CODE REVIEW

**Comment by Saipradyumnagoud** [comment]
@Anushkabh  please review the pull request

**Comment by himanshu-03** [comment]
@Saipradyumnagoud you were not even assigned the issue and you created a PR before that?

**Comment by Saipradyumnagoud** [comment]
> @Saipradyumnagoud you were not even assigned the issue and you created a PR before that?

Yes sorry this will not be repated

**Comment by himanshu-03** [comment]
Please open an issue first @Saipradyumnagoud !

**Comment by Saipradyumnagoud** [comment]
> Please open an issue first @Saipradyumnagoud !

this issue was opened by me @himanshu-03

**Comment by himanshu-03** [comment]
Hey @Saipradyumnagoud !

image

While you replaced RP with rupee icon, the Rp in this link also got replaced. fix this and let me know

**Review by Saipradyumnagoud — COMMENTED** [review]
@himanshu-03 made the changes you requested

**Comment by himanshu-03** [comment]
Great!

**Comment by himanshu-03** [comment]
> @himanshu-03 made the changes you requested

Why is there a dot ahead of each symbol? I dont think we should have a dot there

**Comment by Saipradyumnagoud** [comment]
> > @himanshu-03 made the changes you requested
> 
> Why is there a dot ahead of each symbol? I dont think we should have a dot there

should i remove even dot?

**Review by Saipradyumnagoud — COMMENTED** [review]
@himanshu-03 Made teh changes you reqired

**Comment by himanshu-03** [comment]
LGTM!

**Pull request merged**
