### PR TITLE
Updated chatbot #789

### PR DESCRIPTION
**Pull request by DevNandini02**
Solved the problem that was coming due to chatbot. #789 

krishi_bug_solved

### CODE REVIEW

**Comment by DevNandini02** [comment]
@RitiChandak earlier i was given level 3 for this issue but you changed to level 1. I have created a completely new working chatbot. It answers users queries using AI as well as given knowledge base. Also it works according to user intent. 
Please consider giving it higher level.

**Comment by RitiChandak** [comment]
that depends on the PR according to that PR i changed the level

**Comment by RitiChandak** [comment]
image
can we decrease the response time?

**Comment by DevNandini02** [comment]
> image can we decrease the response time?

@RitiChandak no we can't control the response time. It takes its own time to check through the knowledge base and respond.

**Comment by RitiChandak** [comment]
image
after yes i am still waiting

**Comment by DevNandini02** [comment]
> image after yes i am still waiting

@RitiChandak after typing yes you need to straight away write your question. Then it will answer

**Pull request merged**
