### PR TITLE
Enhanced the FAQ Section

### LINKED ISSUE #739: Feat:Enhancing the FAQ section
### Describe the feature

Enchancing the FAQ section it is not properly fit in the webpage

### Add ScreenShots

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Saipradyumnagoud**
Enhanced the footer 

before
image

after 
image

Closes #739

### CODE REVIEW

**Comment by Saipradyumnagoud** [comment]
@himanshu-03 I have enchanced the footer you can please review it now

**Comment by himanshu-03** [comment]
The whole FAQ cards and the top banner isnt going nicely with the website. Also, sync your changes from our main repo our footer and header both are updated.

**Comment by Saipradyumnagoud** [comment]
> der both are updated.

Give me some time i will update

**Comment by Saipradyumnagoud** [comment]
@himanshu-03 Please review it now

**Comment by himanshu-03** [comment]
> @himanshu-03 Please review it now and also could you please change the level 1 -> level 2

The main changes are just in aligning them to the whole page, it will be counted as level 1 only.

**Comment by Saipradyumnagoud** [comment]
> > @himanshu-03 Please review it now and also could you please change the level 1 -> level 2
> 
> The main changes are just in aligning them to the whole page, it will be counted as level 1 only.

Lot of changes in the code i hope @himanshu-03

**Pull request merged**
