### PR TITLE
Oil seeds

### LINKED ISSUE #562: Feat: Design oil seeds page
### Describe the feature

@RitiChandak 

check this 
we can add new page `/oil-seeds` when user click on this option they will redirected here

### Add ScreenShots

image

we can design oil seeds something like this
image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by dhruv8433**
@Anushkabh 

# please add `level 3`

Feat: Design oil seeds page #562

close #562

### screenshorts

- large screen

image

- medium devices

image

- small devices

image

### CODE REVIEW

**Comment by dhruv8433** [comment]
@Anushkabh 

please check this and merge it
also add `level 3` lable

i added 
- new route `/Oil-seeds`
- support theme based
- make it responsive in all devices

**Comment by dhruv8433** [comment]
@Anushkabh 

please check this and merge it
also add `level 3` lable

i added 
- new route `/Oil-seeds`
- support theme based
- make it responsive in all devices

**Comment by dhruv8433** [comment]
@Anushkabh 


Kindly please check this and merge it

**Comment by dhruv8433** [comment]
@Anushkabh 
@RitiChandak 

Please mege this
And also add `level 3` lable

**Comment by dhruv8433** [comment]
@Anushkabh 
@RitiChandak 

kindly please check this and merge it

**Comment by dhruv8433** [comment]
@Anushkabh

kindly please check this and merge it

**Comment by dhruv8433** [comment]
@Anushkabh 
@RitiChandak 

Kindly please check this and merge it

**Comment by dhruv8433** [comment]
@Anushkabh
@RitiChandak

Kindly please check this and merge it

**Comment by dhruv8433** [comment]
@Anushkabh
@RitiChandak

Kindly please check this and merge it
so i can make another pr

**Comment by himanshu-03** [comment]
Hello @dhruv8433 !

I have seen the same website design and the banners before. Are you  a 100 percent sure that this iss not plagiarized? Because I do think it is.

**Comment by dhruv8433** [comment]
Hey @himanshu-03 

I just use the same layout, but the content was changed in every particular route

**Comment by himanshu-03** [comment]
Okay you start working on them. I have closed your previous issues regarding the same. Reopen them and tag me i will assign you them each one by one.

**Comment by dhruv8433** [comment]
@himanshu-03 

Okay and please merge this

**Comment by himanshu-03** [comment]
Hey @dhruv8433 

You have synced the repo changes, so your files should be arranged accordingly with proper routes. You cant have those files in the root directory now. Please do the necessary changes ASAP

**Comment by dhruv8433** [comment]
@himanshu-03 

i pulled upstream and update code as you mention
now you can merge it

**Comment by dhruv8433** [comment]
@himanshu-03 

ok i just removed it

**Comment by himanshu-03** [comment]
> @himanshu-03
> 
> ok i just removed it

You did the changes iin shop.html right?

Because they both were same files somene just created its copy

**Comment by dhruv8433** [comment]
@himanshu-03 

yeah i added `oil seeds` route in shop.html

**Comment by himanshu-03** [comment]
@dhruv8433 You might have same layoout but the content says Fruits in its banner, title bar, footer.

image
image
image
image


You need to make this changes acording to oil seeds.

**Comment by himanshu-03** [comment]
Also, there is no official website footer or header in the page.

**Comment by himanshu-03** [comment]
> Also, there is no official website footer or header in the page.

Try to keep the header and the footer of the page same as the website. For now it just looks like a html page I cannot see anywhere whether it is a part of krishiconnect or not

**Comment by dhruv8433** [comment]
Got it

**Comment by dhruv8433** [comment]
@himanshu-03 

image

image

**Comment by dhruv8433** [comment]
@himanshu-03 

Ok i will implement it

**Comment by himanshu-03** [comment]
> @himanshu-03
> 
> Ok i will implement it

yes my advice will be instead of going for multiple issues try implementing all functionalities in one, you can then make n number of pages for it.

**Comment by himanshu-03** [comment]
image

this needs to be changed as well

**Comment by dhruv8433** [comment]
@himanshu-03 

now you can check this as you say, i update code and added the cards that already designed

**Comment by dhruv8433** [comment]
image

**Review by himanshu-03 — CHANGES_REQUESTED** [review]
Please sync the changes our footer and navbar both are updated now. Also, add a black  transaparency effect on half of the left side so that the text there is visible. Or add transparency to the whole section.

image

**Comment by dhruv8433** [comment]
@himanshu-03 

image

**Comment by himanshu-03** [comment]
> @himanshu-03
> 
> image

Why are you not sycning the changes from the main repo. Our repo has updated the footer headers, chatbots.

**Comment by dhruv8433** [comment]
@himanshu-03 

sorry now you can merge this

**Comment by dhruv8433** [comment]
@himanshu-03 

i sync the changes and update oil seeds page as per layout

image

**Comment by dhruv8433** [comment]
@himanshu-03

i sync the changes and update oil seeds page as per layout
kindly please check this and merge it

**Pull request merged**
