### PR TITLE
added thank you modal

### PR DESCRIPTION
**Pull request by nandani-goyal**
solves: #648 
I have added the thank you modal. It has a "ok" button which closes the modal. I have also added confetti effect.

https://github.com/Anushkabh/krishiconnect/assets/152094228/15507e98-aeef-4f6a-b646-ceaff2115b3d

### CODE REVIEW

**Review by himanshu-03 — CHANGES_REQUESTED** [review]
image

It displays this even when the cart is empty and order button is clicked

**Comment by nandani-goyal** [comment]
ok I will improve resolve the issue.

**Comment by nandani-goyal** [comment]
you can review the pull request i have resolved the issue. Now the thank You message pops up only when cart is filled.
[Screen Recording 2024-07-02 180158.zip](https://github.com/user-attachments/files/16068185/Screen.Recording.2024-07-02.180158.zip)

**Comment by nandani-goyal** [comment]
Screenshot 2024-07-02 180651

image

**Review by himanshu-03 — APPROVED** [review]
LGTM!

**Pull request merged**
