### PR TITLE
enhanced the Rate Us page 

### PR DESCRIPTION
**Pull request by anagha-chaudhari**
Fixes Issue #659 

The rate us page is enhanced and a toastify message is displayed upon hitting submit. Please review the PR and if there are any changes that are required, I will do so accordingly

Screenshot:

rateus1

rateus2

Demo:

https://github.com/Anushkabh/krishiconnect/assets/143149376/3342a7c8-a130-4867-a6fa-85905d34931e

### CODE REVIEW

**Review by himanshu-03 — CHANGES_REQUESTED** [review]
Please make the container bg a little more dark its near to transparent.

**Comment by anagha-chaudhari** [comment]
Is this much okay @himanshu-03 

rateus

**Comment by anagha-chaudhari** [comment]
I have resolved merge conflicts, please review @himanshu-03

**Comment by anagha-chaudhari** [comment]
Updated the navbar as well

**Comment by himanshu-03** [comment]
> Updated the navbar as well

Theres one small issue the navbar remains fixed  on the screen.

**Comment by anagha-chaudhari** [comment]
I have fixed the issue, please check @himanshu-03

**Comment by anagha-chaudhari** [comment]
@himanshu-03 please review

**Pull request merged**
