### PR TITLE
adding social media icons to footer

### PR DESCRIPTION
**Pull request by Syed0206**

### CODE REVIEW

**Comment by Anushkabh** [comment]
@Syed0206  KINDLY MENTION THE ISSUE NUMBER

**Comment by Syed0206** [comment]
Issue number is 118 Sir.

**Comment by Anushkabh** [comment]
@Syed0206 share the ss of your changes

**Comment by Syed0206** [comment]
Screenshot 2024-05-16 at 4 43 19 PM

**Comment by Syed0206** [comment]
Sir sent you ss  can you please review it and merge my pull request.

**Comment by himanshu-03** [comment]
Fixes #118

**Pull request merged**
