### PR TITLE
solve the hover effect on the social media icons in all the pages

### LINKED ISSUE #912: BUG:issue in icon hover effect
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

in footer when i hover on the social media icon then disable or fully white display

image

we can in hover effect display like actual icons 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Varsani2520**
i Fixed #912 

i check all the pages and solved hover issue :
now perfectly work in all the pages

### CODE REVIEW

**Comment by Varsani2520** [comment]
@RitiChandak ,review it and merged it

**Comment by Varsani2520** [comment]
@RitiChandak ,please menrged it

**Comment by RitiChandak** [comment]
conflicting file please resolve 
image

**Comment by Varsani2520** [comment]
@RitiChandak ,i fixed the conflicts .

**Comment by Varsani2520** [comment]
@RitiChandak ,please merged my PR i solve the Conflict

**Comment by Varsani2520** [comment]
@RitiChandak , i requested you to please merged it with level label

**Pull request merged**
