### PR TITLE
contact.html file do in set and also give well structure

### PR DESCRIPTION
**Pull request by Varsani2520**
image
#520 
@RitiChandak 
check it and merge it 

also add label gssoc and level1 ,2,3 ..

### CODE REVIEW

**Comment by RitiChandak** [comment]
@Varsani2520 please resolve
change the color of navbar from black to white and also reduce the size
image

**Review by Varsani2520 — COMMENTED** [review]
i review it

**Comment by Varsani2520** [comment]
Hey @RitiChandak ,now check it

**Comment by Varsani2520** [comment]
image

**Comment by Varsani2520** [comment]
Hey @RitiChandak ,give a response as well as merge it

**Comment by himanshu-03** [comment]
Fixes #520

**Pull request merged**
