### PR TITLE
Fruites page

### LINKED ISSUE #345: Feat: Add Beautiful Detailed Fruits Page
### Describe the feature

@Anushkabh 

we can build beautiful fruits page for better user experience

### Add ScreenShots

from this in single page

image

to
we can build something like this

image

please assign me i want to work on that

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by dhruv8433**
@Anushkabh 

description:
Feat: Add Beautiful Detailed Fruits Page #345

close #345

check this out: 
- i created `fruits` page when user click on fruits 

image

- they will redirect to this page [route: `/fruits`]

image

- also added hover effect on fruits card

image

- in responsive it look like

image

### CODE REVIEW

**Comment by dhruv8433** [comment]
@Anushkabh 

if you have free time then please check this and merge it

**Comment by RitiChandak** [comment]
hi @dhruv8433 

image

Remove White Space and Fit Content on the Page

**Comment by dhruv8433** [comment]
Ok

**Comment by dhruv8433** [comment]
@Anushkabh 

now you can check it and merge it
i removed white space

image

**Comment by RitiChandak** [comment]
@dhruv8433 Done!

**Pull request merged**
