### PR TITLE
Feat:want to add search bar in shop page #612

### PR DESCRIPTION
**Pull request by nishant0708**
Feat:want to add search bar in shop page #612 

Added Search Bar
-Search by Name and categories 
-Working with both dark and light Mode
-Make Sure All the functionalities that was happening in orignal cards happens with these card as well
-ensured all details are same both in cards and search result

https://github.com/Anushkabh/krishiconnect/assets/101548649/dbad6ec2-d2e2-42ea-b334-fc9f688c37b9

https://github.com/Anushkabh/krishiconnect/assets/101548649/b433b0f6-440f-4f8c-a662-524962a51a79

hey @himanshu-03  i know you assigned it level 2 but can you please assign it level 3 because there was genuinely a lot of work compare to level 2 pr  as i have to enter every data manually i hope you understand that as shop.html has code of over 1800 lines

### CODE REVIEW

**Comment by himanshu-03** [comment]
Great job there @nishant0708

**Review by himanshu-03 — APPROVED** [review]
LGTM!

**Comment by himanshu-03** [comment]
Just a small change the yellow color on hover isnt looking good, i think we can keep it basic white just type the text and results show. the yellow color isnt  really matching, or try to add a little greyish bg (i hope you are getting what I am trying to say what we look in e commerce websites)

**Comment by himanshu-03** [comment]
> Just a small change the yellow color on hover isnt looking good, i think we can keep it basic white just type the text and results show. the yellow color isnt really matching, or try to add a little greyish bg (i hope you are getting what I am trying to say what we look in e commerce websites)

Try adding the search icon in the rightmost side of the box too like u mentioned in the issue.

**Comment by nishant0708** [comment]
> > Just a small change the yellow color on hover isnt looking good, i think we can keep it basic white just type the text and results show. the yellow color isnt really matching, or try to add a little greyish bg (i hope you are getting what I am trying to say what we look in e commerce websites)
> 
> Try adding the search icon in the rightmost side of the box too like u mentioned in the issue.

Okay @himanshu-03 I will complete it by evening and let u know but please reconsider this pr of level 3

**Comment by himanshu-03** [comment]
> > > Just a small change the yellow color on hover isnt looking good, i think we can keep it basic white just type the text and results show. the yellow color isnt really matching, or try to add a little greyish bg (i hope you are getting what I am trying to say what we look in e commerce websites)
> > 
> > 
> > Try adding the search icon in the rightmost side of the box too like u mentioned in the issue.
> 
> Okay @himanshu-03 I will complete it by evening and let u know but please reconsider this pr of level 3

Uhmm I am afraid that wont be happening @nishant0708

**Comment by nishant0708** [comment]
> > > > Just a small change the yellow color on hover isnt looking good, i think we can keep it basic white just type the text and results show. the yellow color isnt really matching, or try to add a little greyish bg (i hope you are getting what I am trying to say what we look in e commerce websites)
> > > 
> > > 
> > > Try adding the search icon in the rightmost side of the box too like u mentioned in the issue.
> > 
> > 
> > Okay @himanshu-03 I will complete it by evening and let u know but please reconsider this pr of level 3
> 
> Uhmm I am afraid that wont be happening @nishant0708

Okay @himanshu-03

**Comment by nishant0708** [comment]
hey @himanshu-03  
image
done

**Comment by himanshu-03** [comment]
LGTM!

**Pull request merged**
