### PR TITLE
added google translate

### LINKED ISSUE #548: Add a translation feature
### Describe the feature

add a google translation page to translate the page as preferred by the user

### Add ScreenShots

Screenshot 2024-06-03 161458
add something of this sort

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by samarsajad**
## Description
Added a google translate feature that enables user to translate the page in the desired language.
## Screenshots
image

### CODE REVIEW

**Comment by samarsajad** [comment]
Please review my pull request @Anushkabh

**Comment by himanshu-03** [comment]
please share the screenshot or video demonstration of your work @samarsajad

**Comment by samarsajad** [comment]
> please share the screenshot or video demonstration of your work @samarsajad

I re-uploaded the screenshot. Please take a look @himanshu-03

**Comment by samarsajad** [comment]
Please review my pull request @himanshu-03 @Anushkabh

**Comment by himanshu-03** [comment]
hey @samarsajad !

since this is a level 3 issue, we expect that the google translate function should be visible everytime. Maybe we can add a pop up on the left or rigth hand side of the website with a UI referenced from the website?
Do let me know your thoughts on this!

**Comment by samarsajad** [comment]
> hey @samarsajad !
> 
> since this is a level 3 issue, we expect that the google translate function should be visible everytime. Maybe we can add a pop up on the left or rigth hand side of the website with a UI referenced from the website? Do let me know your thoughts on this!

Alright. I will work on it. Thanks for your feedback @himanshu-03

**Comment by samarsajad** [comment]
I made the changes. Please take a look @Anushkabh @himanshu-03 

https://github.com/Anushkabh/krishiconnect/assets/142666229/910c8d5a-26a0-411b-a3d8-22dc2425494c

**Comment by himanshu-03** [comment]
> I made the changes. Please take a look @Anushkabh @himanshu-03
> 
>  krishi.google.mp4

image

Its not visible properly @samarsajad

**Comment by himanshu-03** [comment]
> > I made the changes. Please take a look @Anushkabh @himanshu-03
> > krishi.google.mp4
> 
> image
> 
> Its not visible properly @samarsajad

Also, try to give it a circled logo like we have for our chatbot. And the pop up should be just above the logo like our chatbot.

**Review by himanshu-03 — CHANGES_REQUESTED** [review]
Changes required

**Comment by samarsajad** [comment]
Can I please open a new pull request for this issue as I am Facing issues in pushing the changes in the same branch? @himanshu-03 @RitiChandak

**Comment by samarsajad** [comment]
this pull requests had issue that couldn't be solved . So I created a new one  #857 Please take a look

**Comment by samarsajad** [comment]
PTAL #857  @himanshu-03 @RitiChandak @Anushkabh

**Pull request closed without merging**
