### PR TITLE
Feat: Reveal items on scroll!!

### PR DESCRIPTION
**Pull request by Anjaliavv51**
issue #108

Login Page After Changes :

https://github.com/Anushkabh/krishiconnect/assets/154777864/c4366a46-1d71-4c3c-846f-a3be51a398a1

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
Index page after changes:

https://github.com/Anushkabh/krishiconnect/assets/154777864/175db888-a82c-40df-b092-4dfe17115694

---

faq page after changes:
[faq page.zip](https://github.com/Anushkabh/krishiconnect/files/15355267/faq.page.zip)

**Comment by Anjaliavv51** [comment]
Cart page after changes:

https://github.com/Anushkabh/krishiconnect/assets/154777864/6aa9e678-91bf-44bf-8708-757880a603af

---

About page after changes:

[about page.zip](https://github.com/Anushkabh/krishiconnect/files/15355273/about.page.zip)

**Comment by Anjaliavv51** [comment]
Settings Page after changes:

https://github.com/Anushkabh/krishiconnect/assets/154777864/69994f26-911a-4bed-b520-421b4f84e0ed

---

Wishlist page after changes:

https://github.com/Anushkabh/krishiconnect/assets/154777864/d0006e16-d0b9-498e-b472-c4a03ea15278

**Comment by Anushkabh** [comment]
good work  but do just one change.. undo the changes in index page .. rest all is good

**Review by Anjaliavv51 — COMMENTED** [review]
The changes in index page completed.

**Comment by Anjaliavv51** [comment]
done

**Pull request merged**
