### PR TITLE
Added new page for vegetables with functionality to add to cart and wishlist

### LINKED ISSUE #791: Feat: Making a page for vegetables including functionalities
### Describe the feature

- Earlier vegetable page didnt match with the theme of our project like shop page
- I made a page of vegetables , matching the theme of the project along with the functionality of add to cart and wishlist , making it more user friendly

### Add ScreenShots

Before:

https://github.com/Anushkabh/krishiconnect/assets/162733812/c42cac5c-b991-44b7-89ba-80c1d881fbf5

After :

https://github.com/Anushkabh/krishiconnect/assets/162733812/f54e89b1-02e0-4fae-8fcc-b288046e6070

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Maana-Ajmera**
fixes #791 

- Added new page of Fruits
- Included functionality of add to cart like in shop page
- Included functionality of add to wishlist like in shop page

Before :

https://github.com/Anushkabh/krishiconnect/assets/162733812/c42cac5c-b991-44b7-89ba-80c1d881fbf5

After:

https://github.com/Anushkabh/krishiconnect/assets/162733812/6a8cd26d-1153-4d55-a517-c70ed24bcced

### CODE REVIEW

**Comment by Maana-Ajmera** [comment]
@himanshu-03 Please review my PR and merge it.

**Comment by Maana-Ajmera** [comment]
@himanshu-03 @RitiChandak Please review my PR and merge it

**Comment by Maana-Ajmera** [comment]
@RitiChandak @himanshu-03 Please review my PR and merge it under gssoc

**Comment by RitiChandak** [comment]
image
please resolve Conflicting files

**Comment by Maana-Ajmera** [comment]
@RitiChandak @himanshu-03 resolved the conflicts , please merge it

**Pull request merged**
