### PR TITLE
Enhanced Cart page 

### PR DESCRIPTION
**Pull request by Amruta7203**
Enhanced the Cart page:
1. Removed content overflow
2. Removed unwanted horizontal scroll bar
3. reduced the opacity of background image for better visual appeal
4. Created a semi transparent navbar instead of fully dark one

before:
image
image
image

after:
image
image
image

### CODE REVIEW

**Comment by Amruta7203** [comment]
Hello @himanshu-03 Review this PR and add relevant gssoc labels

**Comment by himanshu-03** [comment]
Resolve merge conflicts @Amruta7203

**Comment by Amruta7203** [comment]
@himanshu-03 This was a level 2 issue right?

**Comment by himanshu-03** [comment]
> @himanshu-03 This was a level 2 issue right?

It was because I thought you were saying of completely changing the page design. However only overflow and few stylings were updated.

**Comment by himanshu-03** [comment]
> > @himanshu-03 This was a level 2 issue right?
> 
> It was because I thought you were saying of completely changing the page design. However only overflow and few stylings were updated.

Should I go merging with the PR?

**Comment by Amruta7203** [comment]
@himanshu-03 should I make some more changes in the page then?

**Comment by RitiChandak** [comment]
Hi @Amruta7203, the level may be adjusted after reviewing your work.

Please change these several things.
the navbar 
image
remove the opacity from the logo
image
Change the text color, or perhaps you've also applied the opacity feature to the image content also.
image

**Comment by Amruta7203** [comment]
@RitiChandak @himanshu-03 I have made the necessary changes.. Review and merge after adding relevant labels.

**Review by RitiChandak — CHANGES_REQUESTED** [review]
image
image
image
image

**Comment by Amruta7203** [comment]
I have raised a new PR for the same @RitiChandak

**Pull request closed without merging**
