### PR TITLE
Added "Privacy Policy" and "Terms and Conditions" Pages 

### LINKED ISSUE #674: Feature💡: Add "Privacy Policy" and "Terms and Conditions" Pages to Footer
### Describe the feature

Hey @RitiChandak and @Anushkabh 

I want to suggest a feature request to you which is essential - 

Currently, the website footer does not have a dedicated section for legal pages. To enhance user experience and ensure compliance, we need to add a new column labeled "LEGAL" in the footer. 
This column should include links to the "Terms and Conditions" and "Privacy Policy" pages.

### What will I Do ? 

1. Modify the footer layout to **include a New Column labeled "LEGAL"**. 
2. **Create a "Terms and Conditions" page** and **Add links** to it in LEGAL Column. 
3. **Create a "Privacy Policy" page** and **Add links** to it in LEGAL Column.  
(**NOTE:** I will Ensure that the new column follows the existing footer styling for consistency)

This is where i will do these tasks. It will be very beneficial to have a LEGAL pages section.
Current footer :
image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by aslams2020**
Hey @Anushkabh, @RitiChandak and @himanshu-03 
issue closes #674 

### Below are the changes I implemented - 
1. **Added a dedicated Terms and conditions page**
2. **Added a dedicated Privacy policy page**
3. **Created A New Column** named **"LEGAL"** in the footer section
4. I **tried my very best to style** the pages **to Follow the theme** of the website.
5. I Also **Added Favicons** to both the pages
6. I **integrated the footer** in the pages for smooth navigation.
7. I **Added the Hover effect and transitions** to the new column.

Here is the footer with new Column "Legal"

image

Below is the Overall implementation - 

https://github.com/Anushkabh/krishiconnect/assets/131389695/5220cd22-6c35-400c-9330-4069e2d951c9

@himanshu-03 Please take a look and review it.

### CODE REVIEW

**Comment by himanshu-03** [comment]
While hovering on them, the left side sections move towards a left a little bit. Fix this and resolve merge conflicts.

**Comment by aslams2020** [comment]
@himanshu-03 Done with the changes!

**Review by himanshu-03 — CHANGES_REQUESTED** [review]
image

The page is disoriented.

**Comment by aslams2020** [comment]
@himanshu-03 , I just added the new Column Named "LEGAL" and two pages in ONLY THE FOOTER. I think it's someone else's work whose PR was merged before mine which broke that section. Because i think the page orientation is not related to footer.

**Pull request closed without merging**
