### PR TITLE
Redesign shop

### LINKED ISSUE #493: BUG: Shop Page Style changed
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@Anushkabh 

check this out,

image

shop page card layout and whole style changed

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by dhruv8433**
@RitiChandak 

BUG: Shop Page Style changed #493
close #493

check this out

image

i redeisng shop page and remove other section beacuse we already created seperate page for that
please tell me if you want any modifications

### CODE REVIEW

**Comment by dhruv8433** [comment]
@RitiChandak 

Got it

**Comment by dhruv8433** [comment]
@RitiChandak 

now you can check this and merge it

**Comment by dhruv8433** [comment]
@RitiChandak 

i modified text of shop page

image

now you can merge it

**Comment by RitiChandak** [comment]
image
the navbar is transparent do it similar like this
image

also the text "shopping page " should be similar like transaction page

**Comment by dhruv8433** [comment]
ok i will do it

**Comment by dhruv8433** [comment]
@RitiChandak 

image

please check this and merge it
if you want any modification please inform me

**Comment by RitiChandak** [comment]
@dhruv8433 it is visible now 
image
but as i scroll down and come back 
image
it look like this

**Comment by dhruv8433** [comment]
ok i will check

**Comment by dhruv8433** [comment]
@RitiChandak 

now it will perfect

image

now you can merge it

**Comment by dhruv8433** [comment]
@RitiChandak 

please check this and merge it

**Pull request merged**
